import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const rootDir = process.cwd()
const hubHtml = fs.readFileSync(path.resolve(rootDir, "web-asset/admin/portal-hub.html"), "utf8")
const studentAdminHtml = fs.readFileSync(
  path.resolve(rootDir, "web-asset/admin/student-admin.html"),
  "utf8",
)
const studentAdminJs = fs.readFileSync(
  path.resolve(rootDir, "web-asset/admin/student-admin.js"),
  "utf8",
)
const studentAdminCss = fs.readFileSync(
  path.resolve(rootDir, "web-asset/admin/student-admin.css"),
  "utf8",
)
const sharedPortalThemeCss = fs.readFileSync(
  path.resolve(rootDir, "web-asset/shared/portal-theme.css"),
  "utf8",
)

test("portal ladder surfaces are labeled explicitly in markup", () => {
  assert.match(hubHtml, /<body class="portal-hub-page" id="top" data-surface-role="page">/)
  assert.match(hubHtml, /<div class="header-bar" data-surface-role="content">/)
  assert.match(hubHtml, /<section class="card hero" aria-labelledby="hub-title" data-surface-role="content">/)
  assert.match(hubHtml, /<section class="card section-card section-card--primary" aria-labelledby="primary-portals" data-surface-role="content">/)
  assert.match(hubHtml, /<section class="card hub-prefooter" aria-label="Support links" data-surface-role="content">/)
  assert.match(hubHtml, /data-surface-role="card"/)

  assert.match(studentAdminHtml, /<div class="content page-section" data-page="profile" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<main class="section-stack" id="appMain" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content app-page-header" id="appPageHeader" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content(?: hidden)?" id="topControlsPanel" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<select id="filterLevel" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<select id="filterSchool" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="col-12" id="topSearchResultsPanel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="list-box top-search-results-box data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<button id="topSearchExpandBtn" type="button" class="hidden portal-button portal-button-info">/)
  assert.match(studentAdminHtml, /<div class="panel(?: hidden)?" id="studentListPanel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="list-box data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="student-admin" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content page-section(?: active)?" data-page="overview" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="parent-tracking" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<section class="attendance-level-panel panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section class="attendance-student-panel panel parent-tracking-form" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="progress-report-card card" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="progress-report-table-wrap data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="performance-data" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="table-column-controls data-surface" id="performanceColumnControls" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="performance-data-list data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<section class="hidden panel" id="performanceStagedSection" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section class="hidden panel" id="performanceQueueSection" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<details class="data-surface" id="performanceQueueDetails" data-surface-role="data-surface"(?: open)?>/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="news-reports" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface news-review-table-wrap" data-surface-role="data-surface">[\s\S]*?<tbody id="newsReviewRows">/)
  assert.match(studentAdminHtml, /<div id="newsReviewViewerModal" class="queue-modal hidden" role="dialog" aria-modal="true" aria-label="Student news report detail viewer">[\s\S]*?<div class="queue-modal-card content" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div id="newsReviewViewerBody" class="queue-modal-body panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="news-review-viewer-review card" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="queue-hub" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<p class="small panel" id="queueHubStatus" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div id="queueHubPanels" class="queue-hub-panels">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="attendance" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<section class="attendance-level-panel panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section class="attendance-student-panel panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="assignments" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="assignments-data" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="table-column-controls data-surface" id="assignmentColumnControls" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">[\s\S]*?<tbody id="assignmentItemRows">/)
  assert.match(studentAdminHtml, /<select id="a_quarter" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="grades" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="grades-data" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<section class="grade-chart-shell panel" id="gradeChartShell" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="table-column-controls data-surface" id="gradeColumnControls" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="grade-data-list data-surface" data-surface-role="data-surface">[\s\S]*?<p class="small admin-table-summary" id="gradeDataSummary">/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">[\s\S]*?<tbody id="gradeRows"><\/tbody>/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">[\s\S]*?<tbody id="attendanceLandingRows"><\/tbody>/)
  assert.match(studentAdminHtml, /<div class="content page-section" data-page="attendance-admin" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<select id="attendanceSortField" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<select id="attendanceDataLevel" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<select id="attendanceDataStudent" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="mini-list data-surface" id="attendanceAdminRiskStudents" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">[\s\S]*?<tbody id="attendanceAdminRows"><\/tbody>/)
  assert.match(studentAdminHtml, /<div class="attendance-column-controls data-surface" id="attendanceColumnControls" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="attendance-level-editor panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section id="systemHealthSection" class="overview-group panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section class="overview-group panel" data-surface-role="panel">[\s\S]*?<h3>Today Snapshot<\/h3>/)
  assert.match(studentAdminHtml, /<div class="stat-card stat-card--student card" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="chart-shell data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="chart-shell bar-chart-shell data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" id="overviewClassTableWrap" data-surface-role="data-surface"[^>]*>/)
  assert.match(studentAdminHtml, /<section class="overview-group level-detail-panel panel" id="levelDetailPanel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="mini-list data-surface" id="overviewRiskStudents" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<section class="overview-group full hidden panel" id="overviewIncomingExerciseSection" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<section class="overview-group full panel" id="overviewNewsQueueSection" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div id="profileInfoDataSummary" class="panel profile-info-summary" aria-live="polite" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<select id="profileEnrollmentPeriodSelect" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="profile-layout-editor panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<select id="profileFieldCreateType" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<select id="profileFieldCreateTab" data-surface-role="card">/)
  assert.match(studentAdminHtml, /<div class="profile-layout-table-wrap data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="content" id="status" data-surface-role="content"><\/div>/)
  assert.match(studentAdminHtml, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">[\s\S]*?<tbody id="assignmentTemplateRows">/)
  assert.match(studentAdminHtml, /<div class="content page-section hidden" id="schoolSetupPanel" data-page="school-setup" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="panel school-setup-body" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="table-wrap data-surface school-setup-quarter-table" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="content page-section hidden" id="settingsPanel" data-page="settings" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="panel settings-options-panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="panel settings-mirror-panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="profile-layout-editor panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="attendance-level-editor panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="content page-section hidden" id="userAdminPanel" data-page="users" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="panel user-admin-form" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<div class="table-wrap data-surface user-admin-table" data-surface-role="data-surface">/)
  assert.match(studentAdminHtml, /<div class="content page-section hidden" id="permissionsPanel" data-page="permissions" data-surface-role="content">/)
  assert.match(studentAdminHtml, /<div class="panel permissions-rows-panel" data-surface-role="panel">/)
  assert.match(studentAdminHtml, /<footer class="hub-footer" aria-label="Site footer">/)

  assert.match(studentAdminJs, /<article class="profile-summary-chip card" data-surface-role="card">/)
  assert.match(studentAdminJs, /<article class="profile-summary-primary card" data-surface-role="card">/)
  assert.match(studentAdminJs, /<div class="table-scroll-wrap data-surface" data-surface-role="data-surface">/)
  assert.match(studentAdminJs, /<article class="grade-chart-lane data-surface" data-grade-chart-lane=/)
  assert.match(studentAdminJs, /function studentDisplayLevel\(student = \{\}\) \{/)
  assert.match(studentAdminJs, /student\?\.currentEnrollment\?\.level \|\|/)
  assert.match(studentAdminJs, /const levelName = studentDisplayLevel\(student\);/)
  assert.match(studentAdminJs, /function scrollProfileSurfaceIntoView\(\) \{/)
  assert.match(studentAdminJs, /function openStudentProfileFromList\(studentRefId = ""\) \{/)
  assert.match(studentAdminJs, /setActivePage\("profile"\);\s*scrollProfileSurfaceIntoView\(\);/s)
  assert.match(studentAdminJs, /tr\.addEventListener\("click", \(\) => openStudentProfileFromList\(student\.id\)\);/)
  assert.match(studentAdminJs, /button\.className = `portal-button portal-button-primary profile-tab-button\$\{isActive \? " active" : ""\}`;/)
  assert.doesNotMatch(studentAdminJs, /const chipStyle = \[/)
  assert.doesNotMatch(studentAdminJs, /const chipAttrs = `style="\$\{escapeHtml\(chipStyle\)\}"`;/)
  assert.doesNotMatch(studentAdminJs, /<span class="\$\{classes\}" \$\{chipAttrs\}>/)
  assert.match(sharedPortalThemeCss, /body\.admin-portal-page \.level-chip \{/)
  assert.match(sharedPortalThemeCss, /body\.admin-portal-page \.level-chip\.panelbg-fly \{/)
  assert.match(sharedPortalThemeCss, /body\.admin-portal-page \.level-chip\.panelbg-private \{/)
  assert.doesNotMatch(studentAdminCss, /\.level-chip \{/)
  assert.doesNotMatch(studentAdminCss, /\.level-chip\.panelbg-fly \{/)
  assert.match(studentAdminJs, /panelEl\.className = `queue-hub-panel panel/)
  assert.match(studentAdminJs, /panelEl\.dataset\.surfaceRole = "panel";/)
  assert.match(studentAdminJs, /select\.dataset\.surfaceRole = "card";/)
  assert.match(studentAdminJs, /item\.dataset\.surfaceRole = "card";/)
  assert.match(studentAdminJs, /wrapper\.dataset\.surfaceRole = "card";/)
  assert.match(studentAdminJs, /item\.className = "profile-choice-item card";\s*item\.dataset\.surfaceRole = "card";/s)
  assert.match(studentAdminJs, /panel\.dataset\.surfaceRole = "panel";/)
  assert.match(studentAdminJs, /card\.className = "permission-role-card card";\s*card\.dataset\.surfaceRole = "card";/s)
  assert.match(studentAdminCss, /\.page-section \.actions > :is\(button, a, summary, \.portal-button, \.link-btn\) \{/)
  assert.match(studentAdminCss, /\.top-search-open-btn,\s+\.portal-button-open-week-set,\s+\.queue-row-btn \{/)
  assert.doesNotMatch(studentAdminCss, /#topSearchExpandBtn \{[\s\S]*min-height: 36px;/s)
  assert.match(studentAdminCss, /\.page-section\[data-page="profile"\] \.actions button \{\s*font-size: 14px;\s*min-height: 48px;/s)
  assert.match(
    sharedPortalThemeCss,
    /body\.admin-portal-page \.profile-tab-nav button \{\s*background: var\(--portal-button-fill\);\s*border: 1px solid var\(--portal-button-stroke\);\s*color: var\(--portal-button-ink\);/s,
  )
  assert.doesNotMatch(sharedPortalThemeCss, /body\.admin-portal-page \.profile-tab-nav button \{[^}]*box-shadow: none;/s)
  assert.match(
    sharedPortalThemeCss,
    /body\.admin-portal-page \.profile-tab-nav button:hover:not\(:disabled\),\s*body\.admin-portal-page \.profile-tab-nav button:focus-visible \{\s*background: var\(--portal-button-fill-hover\);\s*border-color: var\(--portal-button-stroke-hover\);\s*color: var\(--portal-button-ink-hover\);/s,
  )
  assert.match(
    sharedPortalThemeCss,
    /html\[data-theme="dark"\] body\.admin-portal-page .profile-tab-nav button \{\s*background: var\(--portal-button-fill\);\s*border-color: var\(--portal-button-stroke\);\s*color: var\(--portal-button-ink\);/s,
  )
  assert.match(
    studentAdminCss,
    /\.profile-tab-nav \.profile-tab-button \{[\s\S]*min-inline-size: var\(--portal-button-inline\);/s,
  )
  assert.match(studentAdminCss, /\.profile-tab-nav button \{[\s\S]*flex: 0 0 auto;[\s\S]*width: auto;/s)
  assert.doesNotMatch(studentAdminCss, /\.profile-tab-nav \{[^}]*overflow-x: auto;/s)
  assert.doesNotMatch(studentAdminCss, /\.profile-tab-nav \{[^}]*scroll-snap-type: x proximity;/s)
  assert.doesNotMatch(studentAdminCss, /\.profile-tab-nav button \{[^}]*border-radius: var\(--radius-pill\);/s)
  assert.doesNotMatch(sharedPortalThemeCss, /profile-tab-nav button \{[^}]*portal-status-info-bg/s)
  assert.match(studentAdminCss, /\.page-section\[data-page="news-reports"\] \.table-toolbar button \{/)
  assert.doesNotMatch(studentAdminCss, /\.page-section\[data-page="news-reports"\] \.table-toolbar button \{[^}]*width: 100%;/s)
})
